[package]
name = "halo_example"
version = "0.1.0"
edition = "2021"

[dependencies]
group = "0.13.0"
halo2 = "0.0.0"
halo2_proofs = "0.3.0"
halo2_gadgets = {version = "0.3.1", features = ["unstable-sha256-gadget"]}
hex = "0.4.3"
rand = "0.8.5"
